from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from src.api.auth import create_access_token, hash_password, verify_password
from src.api.db import get_db
from src.api.models import User
from src.api.schemas import RegisterRequest, LoginRequest, TokenResponse, UserPublic

router = APIRouter(prefix="/auth", tags=["auth"])


@router.post(
    "/register",
    response_model=UserPublic,
    status_code=201,
    summary="Register a new user",
    description="Create a new user account with email/password.",
)
def register(req: RegisterRequest, db: Session = Depends(get_db)) -> UserPublic:
    """Register a new user."""
    existing = db.query(User).filter(User.email == req.email.lower()).first()
    if existing:
        raise HTTPException(status_code=409, detail="Email already registered.")

    now = datetime.now(timezone.utc)
    user = User(
        # id generated by DB default in schema; but ORM requires a value if not using server_default mapping.
        # We'll let DB generate by selecting gen_random_uuid() via INSERT default by omitting id.
        # SQLAlchemy mapped_column without server_default means we need a value; set here.
        id=__import__("uuid").uuid4(),
        email=req.email.lower(),
        password_hash=hash_password(req.password),
        display_name=req.display_name,
        created_at=now,
        updated_at=now,
    )
    db.add(user)
    db.commit()
    db.refresh(user)
    return UserPublic.model_validate(user)


@router.post(
    "/login",
    response_model=TokenResponse,
    summary="Login",
    description="Authenticate a user and return a JWT bearer token.",
)
def login(req: LoginRequest, db: Session = Depends(get_db)) -> TokenResponse:
    """Login and get JWT token."""
    user = db.query(User).filter(User.email == req.email.lower()).first()
    if not user or not verify_password(req.password, user.password_hash):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid credentials.")
    token = create_access_token(user.id)
    return TokenResponse(access_token=token, token_type="bearer")
